[server]
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#004A99"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#0b2b45"
